x-service-base: &service-base
  extra_hosts:
    - 'host.docker.internal:host-gateway'
  stdin_open: true
  tty: true


services:
  dsp:
    <<: *service-base
    build:
      context: dsp
    env_file:
      - docker-compose/env/zeebe.env
    #healthcheck:
    #  test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/8000'
    #  interval: 5s
    #  timeout: 5s
    #  retries: 12
    ports:
      - '9000:8000'
    volumes:
      - ./dsp/dsp/:/app/dsp/

  dsp-worker:
    <<: *service-base
    build:
      context: dsp-worker
    env_file:
      - docker-compose/env/zeebe.env
    #healthcheck:
    #  test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/8000'
    #  interval: 5s
    #  timeout: 5s
    #  retries: 12
    volumes:
      - ./dsp-worker/dsp_worker/:/app/dsp_worker/
